export const videos = [
    {
        id: 'rOUuGvJkBrQ&list=RDrOUuGvJkBrQ&start_radio=1',
        title: "React Full Course for Beginners",
        channel: "Code Academy",
        views: "120K",
        time: "2 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
        id: 2,
        title: "Learn Tailwind CSS in 30 Minutes",
        channel: "Frontend Mastery",
        views: "45K",
        time: "1 week ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
        id: 3,
        title: "JavaScript ES6 Crash Course",
        channel: "Dev Simplified",
        views: "300K",
        time: "3 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 4,
        title: "Build a YouTube Clone with React",
        channel: "Tech Tutorials",
        views: "90K",
        time: "4 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=4",
    },
    {
        id: 5,
        title: "FastAPI Crash Course",
        channel: "Python Dev",
        views: "75K",
        time: "5 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=5",
    },
    {
        id: 6,
        title: "Node.js API Tutorial",
        channel: "Backend Hub",
        views: "210K",
        time: "6 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=6",
    }, {
        id: 7,
        title: "React Full Course for Beginners",
        channel: "Code Academy",
        views: "120K",
        time: "2 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
        id: 8,
        title: "Learn Tailwind CSS in 30 Minutes",
        channel: "Frontend Mastery",
        views: "45K",
        time: "1 week ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
        id: 9,
        title: "JavaScript ES6 Crash Course",
        channel: "Dev Simplified",
        views: "300K",
        time: "3 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 10,
        title: "Build a YouTube Clone with React",
        channel: "Tech Tutorials",
        views: "90K",
        time: "4 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=4",
    },
    {
        id: 11,
        title: "FastAPI Crash Course",
        channel: "Python Dev",
        views: "75K",
        time: "5 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=5",
    },
    {
        id: 12,
        title: "Node.js API Tutorial",
        channel: "Backend Hub",
        views: "210K",
        time: "6 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=6",
    },
    {
        id: 13,
        title: "React Full Course for Beginners",
        channel: "Code Academy",
        views: "120K",
        time: "2 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
        id: 14,
        title: "Learn Tailwind CSS in 30 Minutes",
        channel: "Frontend Mastery",
        views: "45K",
        time: "1 week ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
        id: 15,
        title: "JavaScript ES6 Crash Course",
        channel: "Dev Simplified",
        views: "300K",
        time: "3 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 16,
        title: "Build a YouTube Clone with React",
        channel: "Tech Tutorials",
        views: "90K",
        time: "4 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=4",
    },
    {
        id: 17,
        title: "FastAPI Crash Course",
        channel: "Python Dev",
        views: "75K",
        time: "5 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=5",
    },
    {
        id: 18,
        title: "Node.js API Tutorial",
        channel: "Backend Hub",
        views: "210K",
        time: "6 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=6",
    },
    {
        id: 19,
        title: "React Full Course for Beginners",
        channel: "Code Academy",
        views: "120K",
        time: "2 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
        id: 20,
        title: "Learn Tailwind CSS in 30 Minutes",
        channel: "Frontend Mastery",
        views: "45K",
        time: "1 week ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
        id: 21,
        title: "JavaScript ES6 Crash Course",
        channel: "Dev Simplified",
        views: "300K",
        time: "3 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 22,
        title: "Build a YouTube Clone with React",
        channel: "Tech Tutorials",
        views: "90K",
        time: "4 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=4",
    },
    {
        id: 23,
        title: "FastAPI Crash Course",
        channel: "Python Dev",
        views: "75K",
        time: "5 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=5",
    },
    {
        id: 24,
        title: "Node.js API Tutorial",
        channel: "Backend Hub",
        views: "210K",
        time: "6 days ago",
        thumbnail: "https://i.ytimg.com/vi/aEu4neydFfs/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOFHTnQbXeEf74Z3Xrhn57OjGXnQ",
        avatar: "https://i.pravatar.cc/40?img=6",
    }
];